services:
  web:
    build: .
    image: "app_web:develop"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./local.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "app_db"
      LC_ALL: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
volumes:
    postgres_data:
