services:
  web:
    build: .
    image: "app_web:develop"
    command: bash -c "python3 manage.py migrate --noinput && gunicorn mainapp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_vol:/app/user_app/static
    ports:
      - 8000:8000
    env_file:
      - ./local.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "app_db"
      LC_ALL: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/user_app/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
    postgres_data:
    static_vol:
